# Generated by Django 3.0.5 on 2021-04-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdbBaseManagement', '0002_auto_20210422_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
