# Generated by Django 3.0.5 on 2021-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdbBaseManagement', '0003_auto_20210422_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_surate',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_write_qurant',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_memorize_quran',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_to_finish_write_qurant',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_to_recit_all_qurant',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_to_start_write_qurant',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_memorize_quran',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_recite_all_qurant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_write_qurant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pseudonyme',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
