# Generated by Django 3.0.5 on 2021-04-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmdbBaseManagement', '0004_auto_20210426_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_write_qurant',
            new_name='current_write_quran',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_finish_write_qurant',
            new_name='date_to_finish_write_quran',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_recit_all_qurant',
            new_name='date_to_recit_all_quran',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_start_write_qurant',
            new_name='date_to_start_write_quran',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_recite_all_qurant',
            new_name='is_recite_all_quran',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_write_qurant',
            new_name='is_write_quran',
        ),
    ]
