# Generated by Django 3.0.5 on 2021-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmdbBaseManagement', '0006_auto_20210426_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_write_quran',
            new_name='current_step_writting',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_write_quran',
            new_name='has_written',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_memorize_quran',
            new_name='memorize_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_finish_write_quran',
            new_name='recite_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_recit_all_quran',
            new_name='writting_begin_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_to_start_write_quran',
            new_name='writting_end_date',
        ),
    ]
